#!/usr/bin/env bash
# instalamos loadbalncer
sudo apt-get update
sudo apt-get install -y haproxy

configurate="
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 34.73.56.247:80 check
    server web-02 35.227.39.162:80 check
    "
sudo chown -R $USER /etc/haproxy/
sudo echo "$configurate" >> /etc/haproxy/haproxy.cfg

sudo service haproxy  restart
